wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1657524961
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      4: 3.8.10
      5: 0.12.21
      8:
      - 1
      - 5
architecture:
  desc: null
  value: GameNet
dataset:
  desc: null
  value: Physionet
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 1.0e-05
num_step_per_epoch:
  desc: null
  value: 19
weightname:
  desc: null
  value: Physionet_Gamenet_64elec_executedImagine_Wandb
