version: '3.9'
services:
  # Service/container name
  python:
    # Optional image name
    image: eeg-emotion-cpu
    # Docker file
    build: 
      context: .
      dockerfile: _cpu.Dockerfile
    # Map volume once container is started
    volumes:
      - ./EEG_Model:/root/EEG_Model
      - ./.vscode-server:/root/.vscode-server
    # Mapping GPU
    deploy:
      resources:
        limits:
          # number of cores this container can use (can be 0.5 means half core)
          cpus: '8'
          # maximun RAM this container can use
          memory: '12G'